#!/bin/sh
_term() {
  echo "C $cmd" | nc -N -U /var/run/cd-port-forward.sock
  kill -INT "$child" 2>/dev/null
}
trap _term INT
# shellcheck disable=SC2124
cmd=$@
echo "O $cmd" | nc -N -U /var/run/cd-port-forward.sock
# shellcheck disable=SC2068
docker-proxy-org $@ &
child=$!
wait "$child"